model_params:
  latent_encoder_dim: 128
  H_dim: 128
  save_model: True
  # inact path: checkpoint/<data_name>/<field>
  model_path: 'checkpoint'
  embedded_visualize: True

data_params:
  data_name: 'shuffled_Scene_2views'
  data_path: 'dataset'
  view_num: 2
  cluster_num: 15
  batch_size: 400 
  num_workers: 0

train_params:
  is_pre_train: False
  is_first_train: False
  is_second_train: False

device_params:
  accelerator: 'gpu'
  devices: [0]

pre_trainer_params:
  pre_lr_ae: 1.0e-3
  pre_max_epochs: 10

first_trainer_params:
  first_lr_ae: 1.0e-3
  first_lr_dg: 1.0e-3
  first_lr_h: 1.0e-3
  first_total_max_epochs: 5
  first_h_max_epochs: 2

second_trainer_params:
  second_lr_ae: 1.0e-3
  second_lr_dg: 1.0e-3
  second_lr_h: 1.0e-4
  second_total_max_epochs: 1
  second_h_max_epochs: 3

log_params:
  # inact path: logs/<data_name>/<field>
  save_log: False
  log_path: 'logs'