model_params:
  latent_encoder_dim: 128
  h_dim: 128
  save_pre_model: True
  pre_model_path: 'checkpoint/pre_models'
  save_model: True
  model_path: 'checkpoint/models'


data_params:
  data_name: 'shuffled_Scene_2views'
  data_path: 'dataset'
  view_num: 2
  cluster_num: 10
  batch_size: 32
  num_workers: 0

exp_params:
  lr_ae: 1.0e-3
  lr_dg: 1.0e-3
  lr_h: 1.0e-3
  lr_pre: 1.0e-3

train_params:
  is_pre_train: True
  is_pre_H: True

pre_trainer_params:
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 3

log_params:
  pre_log_path: "logs/pre_train_logs"
  log_path: "logs/train_logs"
