model_params:
  latent_encoder_dim: 128
  H_dim: 128
  first_model_path: checkpoint/first_models
data_params:
  data_name: shuffled_Scene_2views
  view_num: 2
  cluster_num: 15
  batch_size: 400
  num_workers: 0
device_params:
  accelerator: gpu
  devices:
  - 0
log_params:
  first_log_path: logs/first_train_logs
first_trainer_params:
  first_total_max_epochs: 15
  first_h_max_epochs: 20
  first_lr_ae: 0.001
  first_lr_dg: 0.001
  first_lr_h: 0.001
ae_loss: 0.004435314331203699
dg_loss: 0.0007570942980237305
h_loss: 0.0005185495829209685
model_structure:
  encoder_decoders:
    '[0]':
      encoder:
      - Linear(in_features=20, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=128, bias=True)
      decoder:
      - Linear(in_features=128, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=20, bias=True)
      - Sigmoid()
    '[1]':
      encoder:
      - Linear(in_features=59, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=128, bias=True)
      decoder:
      - Linear(in_features=128, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=59, bias=True)
      - Sigmoid()
  degradation:
    '[0]':
    - Linear(in_features=128, out_features=256, bias=True)
    - ReLU()
    - Linear(in_features=256, out_features=128, bias=True)
    - ReLU()
    '[1]':
    - Linear(in_features=128, out_features=256, bias=True)
    - ReLU()
    - Linear(in_features=256, out_features=128, bias=True)
    - ReLU()
