model_params:
  latent_encoder_dim: 128
  h_dim: 128
data_params:
  data_name: shuffled_Scene_2views
  view_num: 2
  cluster_num: 10
  batch_size: 32
  num_workers: 0
exp_params:
  lr_pre: 0.001
pre_trainer_params:
  accelerator: gpu
  devices:
  - 0
  max_epochs: 3
loss:
  ae_pre_loss: 0.12929418683052063
  view_loss:
    view[0]: 12.036296844482422
    view[1]: 6.194181442260742
model_structure:
  encoder_decoders:
    '[0]':
      encoder:
      - Linear(in_features=20, out_features=128, bias=True)
      - ReLU()
      - Sigmoid()
      decoder:
      - Linear(in_features=128, out_features=20, bias=True)
      - ReLU()
    '[1]':
      encoder:
      - Linear(in_features=59, out_features=128, bias=True)
      - ReLU()
      - Sigmoid()
      decoder:
      - Linear(in_features=128, out_features=59, bias=True)
      - ReLU()
