model_params:
  latent_encoder_dim: 128
  H_dim: 128
  pre_model_path: checkpoint/pre_models
data_params:
  data_name: shuffled_Scene_2views
  view_num: 2
  cluster_num: 15
  batch_size: 400
  num_workers: 0
device_params:
  accelerator: gpu
  devices:
  - 0
pre_trainer_params:
  pre_max_epochs: 100
  pre_lr_ae: 0.001
log_params:
  pre_log_path: logs/pre_train_logs
loss:
  ae_pre_loss: 0.0026148809120059013
  view_loss:
    view[0]: 0.0004823767230845988
    view[1]: 0.0023160437121987343
model_structure:
  encoder_decoders:
    '[0]':
      encoder:
      - Linear(in_features=20, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=128, bias=True)
      decoder:
      - Linear(in_features=128, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=20, bias=True)
      - Sigmoid()
    '[1]':
      encoder:
      - Linear(in_features=59, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=128, bias=True)
      decoder:
      - Linear(in_features=128, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=1024, bias=True)
      - ReLU()
      - Linear(in_features=1024, out_features=59, bias=True)
      - Sigmoid()
